LTO_ENABLE = yes
VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes
TRI_LAYER_ENABLE = yes
COMBO_ENABLE = yes

CAPS_WORD_ENABLE = no
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no